hosts:
  - future.accessibilityexchange.ca
auth:
  - username: colab
    password: colab
  - username: tae
    password: tae
disks:
  - size: 10Gi
    name: accessibility-app-data
env:
  APP_NAME: "The Accessibility Exchange"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://future.accessibilityexchange.ca"
  APP_SERVICE: "future.accessibilityexchange.ca"
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "debug"
  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "sync"
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SAIL_XDEBUG_MODE: "develop,debug,coverage"
  FILES_PATH: "/opt/data/storage"
  # CACHE_PATH: "/opt/data/cache" removed per https://github.com/accessibility-exchange/platform/issues/1596
### Place those values in Vault
# secrets:
#   APP_KEY: ""
#   DB_CONNECTION: ""
#   DB_HOST: ""
#   DB_HOST: ""
#   DB_PORT: ""
#   DB_DATABASE: ""
#   DB_USERNAME: ""
#   DB_PASSWORD: ""
#   MEMCACHED_HOST: ""
#   REDIS_HOST: ""
#   REDIS_PASSWORD: ""
#   REDIS_PORT: ""
#   MAIL_MAILER: ""
#   MAIL_HOST: ""
#   MAIL_PORT: ""
#   MAIL_USERNAME: ""
#   MAIL_PASSWORD: ""
#   MAIL_ENCRYPTION: ""
#   MAIL_FROM_ADDRESS: ""
#   MAIL_FROM_NAME: ""
#   AWS_ACCESS_KEY_ID: ""
#   AWS_SECRET_ACCESS_KEY: ""
#   AWS_DEFAULT_REGION: ""
#   AWS_BUCKET: ""
#   SNAPSHOTS_DISK: ""
#   SNAPSHOTS_AWS_ACCESS_KEY_ID: ""
#   SNAPSHOTS_AWS_SECRET_ACCESS_KEY: ""
#   SNAPSHOTS_AWS_DEFAULT_REGION: ""
#   SNAPSHOTS_AWS_BUCKET: ""
#   PUSHER_APP_ID: ""
#   PUSHER_APP_KEY: ""
#   PUSHER_APP_SECRET: ""
#   PUSHER_APP_CLUSTER: ""
#   VITE_PUSHER_APP_KEY: ""
#   VITE_PUSHER_APP_CLUSTER: ""
#   CIPHERSWEET_KEY: ""
